In [2]:
import os
import pandas as pd

def convert_supplemental_trainset(df_load):
    df_trainset = df_load.drop(df_load[df_load['human CL (mL/min/kg)'].notna()].index)

    df_trainset.drop("human CL (mL/min/kg)", axis=1, inplace=True)
    df_trainset.rename(columns = {'human CL (mL/min/kg)':'Clint'},inplace=True)
    return df_trainset

def convert_supplemental_testset(df_load):
    df_testset = df_load.drop("human CL (mL/min/kg)", axis=1)
    
    df_testset.rename(columns = {'human CL (mL/min/kg)':'Clint'},inplace=True)
    df_testset.dropna(subset=['Clint'], axis=0, inplace=True)
    return df_testset

In [3]:
loaddata_path = "../dataset"
# dataset_file = os.path.join(loaddata_path, "suppplemetal_additionalDataset.csv")
dataset_file = os.path.join(loaddata_path, "train2307_remaked.csv")
df_loaddata = pd.read_csv(dataset_file)

save_path = "../dataset/remake"
rm_duplicates = False

In [3]:
# df_loaddata.dropna(subset=['Clint.invitro.'], axis=0)

df_train = df_loaddata.dropna(subset=['Clint.invitro.'], axis=0)
df_train = df_train.drop(df_train[df_train['Clint.invivo.'].notna()].index)

df_test = df_loaddata[df_loaddata['Clint.invivo.'].notna()]


df_train = df_train.drop("Clint.invivo.", axis=1).reset_index(drop=True)
df_test = df_test.drop("Clint.invitro.", axis=1).reset_index(drop=True)

df_train.rename(columns = {'SMILES_rdkit_final':'SMILES', "Clint.invitro.":"Clint"},inplace=True)
df_test.rename(columns = {'SMILES_rdkit_final':'SMILES', "Clint.invivo.":"Clint"},inplace=True)


# df_trainset = df_loaddata.drop(df_loaddata[df_loaddata['Clint.invivo.'].notna()].index)
# df_testset = df_loaddata.drop("Clint.invitro.", axis=1)

In [4]:
df_train = df_loaddata.dropna(subset=['Clint.invitro.'], axis=0)
df_train = df_train.drop("Clint.invivo.", axis=1).reset_index(drop=True)
df_train.rename(columns = {'SMILES_rdkit_final':'SMILES', "Clint.invitro.":"Clint"},inplace=True)
df_train

,SMILES,logP,Fup,Clint,MW_rdkit,HBD_rdkit,HBA_rdkit,NRB_rdkit,RF_rdkit,PSA_rdkit
0,O=C(CO)N1CCC(c2[nH]nc(-c3ccc(Cl)cc3F)c2-c2ccnc...,1,NaN,3.00,415.12,2,5,4,105.6585,95.00
1,Cc1[nH]nc2c1N=C(c1ccccc1Cl)c1cc([N+](=O)[O-])c...,3.17,0.01350,0.00,353.07,2,5,2,96.4548,96.21
2,Cc1ccc([N+](=O)[O-])cc1,2.37,0.26590,19.32,137.05,0,2,1,37.8334,43.14
3,Cc1ccc(N(C)C)cc1,2.81,0.05498,20.38,135.10,0,1,1,45.5060,3.24
4,COC(=O)c1ccc(O)cc1,1.96,0.07056,107.50,152.05,1,3,1,39.4463,46.53
...,...,...,...,...,...,...,...,...,...,...
1641,OC(c1ccc(-c2ccc(CN3CCN(Cc4ccncc4)CC3)cc2)c(F)c...,NaN,NaN,8.71,527.18,1,4,6,122.6338,39.60
1642,Oc1ccc(Cc2nnc3ncc(-c4ccc(F)cc4)nn23)cc1,2.62,NaN,93.20,321.10,1,6,3,84.8838,76.20
1643,Oc1ccc(Cc2nnc3ncc(-c4ccc(F)cc4)nn23)cc1Cl,3.28,NaN,62.80,355.06,1,6,3,89.8938,76.20
1644,Oc1ccc(Cn2nnc3ncc(-c4ccc(F)cc4)nc32)cc1,2.78,NaN,50.00,321.10,1,6,3,85.7208,76.72
1645,OCCN1CCc2c([nH]c3ccccc23)C1c1ccc(Cl)cc1,3.76,NaN,70.00,326.12,2,2,3,93.9565,39.26

In [5]:
df_train.to_csv("../dataset/remaked/train_nonvivo.csv")

In [13]:
df_train.to_csv("../dataset/remaked/train.csv")
df_test.to_csv("../dataset/remaked/test.csv")

In [45]:
if not "SMILES" in df_loaddata.columns:
    df_loaddata.rename(columns = {'SMILES_rdkit_final':'SMILES'},inplace=True)

    ## -- Remove duplicates SMILES Data -- ##
    if rm_duplicates:
        df_loaddata.drop_duplicates(['SMILES'])

In [46]:
df_loaddata = df_loaddata.loc[:, [col for col in df_loaddata.columns if col == 'human CL (mL/min/kg)' or col == 'SMILES']]

In [47]:
df_loaddata.rename(columns = {'human CL (mL/min/kg)':'Clint'},inplace=True)
df_loaddata.dropna(subset=['SMILES','Clint'], axis=0, inplace=True)

df_loaddata

                                                 SMILES  Clint
0     N1[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(...  25.40
1                    c1cn(c(=O)nc1N)[C@H]2CO[C@H](S2)CO   3.00
2                  c1cn(c(=O)nc1N)[C@@H]2CO[C@@H](S2)CO   3.90
3     O[C@@H]1C[C@@](C[C@@H](OC(=O)\C=C\c2ccc(O)c(O)...   8.70
4     C1([C@@H]2[C@@]3([C@@]([C@@H]4[C@@H]([C@@]5(CC...   0.18
...                                                 ...    ...
1347    OC(=O)CN1C(=O)C(=O)Nc2cc(c(cc12)n3ccnc3)N(=O)=O   5.30
1348     C(=O)(NC(=N)N)c1c(n(nc1)c1c2c(ccc1)nccc2)C1CC1  21.00
1349   CN1CCN(CC1)C(=O)OC2N(C(=O)c3nccnc23)c4ccc(Cl)cn4   3.30
1350  COc1cccc2C(=O)c3c(O)c4C[C@](O)(C[C@H](O[C@H]5C...  22.00
1351  CO[C@@H]1C[C@H](C[C@@H](C)[C@@H]2CC(=O)[C@H](C...   0.67

[1350 rows x 2 columns]

In [48]:

if not "SMILES" in df_loaddata.columns:
    df_loaddata.rename(columns = {'SMILES_rdkit_final':'SMILES'},inplace=True)

    ## -- Remove duplicates SMILES Data -- ##
    if rm_duplicates:
        df_loaddata.drop_duplicates(['SMILES'])

    ## -- delete duplicate invivo and invitro -- ##
    # df_trainset = df_loaddata.drop(df_loaddata[df_loaddata['human CL (mL/min/kg)'].notna()].index)

    df_loaddata = df_loaddata.loc[:, [col for col in df_loaddata.columns if col != 'human CL (mL/min/kg)' or 'SMILES']]
    df_loaddata.rename(columns = {'human CL (mL/min/kg)':'Clint'},inplace=True)

    df_loaddata.dropna(subset=['SMILES','Clint'], axis=0, inplace=True)
    # df_testset.dropna(subset=['SMILES','logP','Clint','Fup'], axis=0, inplace=True)

train_file, test_file = os.path.join(save_path, "train_data_additional.csv"), os.path.join(save_path, "test_data_additional.csv")

df_loaddata.to_csv(train_file, index=False)
# df_testset.to_csv(test_file, index=False)

In [51]:
train_load = pd.read_csv("../dataset/0_NoneOpt/train_data_221027.csv")
train_load_additional = pd.read_csv('../dataset/0_NoneOpt/train_data_additional.csv')

train_load = train_load.loc[:, [col for col in train_load.columns if col == 'Clint' or col == 'SMILES']]
train_load_merge = pd.concat([train_load, train_load_additional])

train_load_merge

                                                 SMILES   Clint
0                       CCn1cc(C(=O)O)c(=O)c2ccc(C)nc21    1.10
1     Cc1c(C)c2c(c(C)c1O)CCC(C)(COc1ccc(CC3SC(=O)NC3...   21.85
2                 CN=C1CN(O)C(c2ccccc2)=c2cc(Cl)ccc2=N1    3.89
3          O=C1CC2(CCCC2)CC(=O)N1CCCCN1CCN(c2ncccn2)CC1    7.66
4                      CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc21  195.10
...                                                 ...     ...
1345    OC(=O)CN1C(=O)C(=O)Nc2cc(c(cc12)n3ccnc3)N(=O)=O    5.30
1346     C(=O)(NC(=N)N)c1c(n(nc1)c1c2c(ccc1)nccc2)C1CC1   21.00
1347   CN1CCN(CC1)C(=O)OC2N(C(=O)c3nccnc23)c4ccc(Cl)cn4    3.30
1348  COc1cccc2C(=O)c3c(O)c4C[C@](O)(C[C@H](O[C@H]5C...   22.00
1349  CO[C@@H]1C[C@H](C[C@@H](C)[C@@H]2CC(=O)[C@H](C...    0.67

[2418 rows x 2 columns]

In [52]:
train_load

                                                 SMILES   Clint
0                       CCn1cc(C(=O)O)c(=O)c2ccc(C)nc21    1.10
1     Cc1c(C)c2c(c(C)c1O)CCC(C)(COc1ccc(CC3SC(=O)NC3...   21.85
2                 CN=C1CN(O)C(c2ccccc2)=c2cc(Cl)ccc2=N1    3.89
3          O=C1CC2(CCCC2)CC(=O)N1CCCCN1CCN(c2ncccn2)CC1    7.66
4                      CN(C)CCCN1c2ccccc2Sc2ccc(Cl)cc21  195.10
...                                                 ...     ...
1063             C#CCOS(=O)OC1CCCCC1Oc1ccc(C(C)(C)C)cc1   24.00
1064          CCc1nn(C)c(C(=O)NCc2ccc(C(C)(C)C)cc2)c1Cl   15.94
1065  CCC(C)C1OC2(C=CC1C)CC1CC(CC=C(C)C(OC3CC(OC)C(O...    0.00
1066  O=C(OCC1OC(OC(=O)c2cc(O)c(O)c(OC(=O)c3cc(O)c(O...    0.00
1067                CCCCCCCCCC[N+](C)(C)Cc1ccccc1.[Cl-]   63.10

[1068 rows x 2 columns]